remote_theme: pages-themes/architect@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
gem "github-pages", group: :jekyll_plugins
title: Paul Kolozsvari's Home Page
description: Paul Kolozsvari's Resume
